/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ClientDialog: typeof import('./components/ClientDialog.vue')['default']
    ClientSwitcher: typeof import('./components/ClientSwitcher.vue')['default']
    EmptyState: typeof import('./components/EmptyState.vue')['default']
    EndpointBuilder: typeof import('./components/EndpointBuilder.vue')['default']
    LoadingState: typeof import('./components/LoadingState.vue')['default']
    LogEntry: typeof import('./components/LogEntry.vue')['default']
    LogViewer: typeof import('./components/LogViewer.vue')['default']
    NavigationRail: typeof import('./components/NavigationRail.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchemaTree: typeof import('./components/SchemaTree.vue')['default']
    SchemaTreeNode: typeof import('./components/SchemaTreeNode.vue')['default']
    SchemaViewer: typeof import('./components/SchemaViewer.vue')['default']
    TestEndpointDialog: typeof import('./components/TestEndpointDialog.vue')['default']
  }
}
